name: CI/CD Process

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew assemble # npm ci da spostare dentro gradle assemble?

  quality-checks:
    runs-on: ubuntu-latest
    needs: [ compile ]
    strategy:
      matrix:
        task: [ test, quality ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}
